version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forest_graphql_admin
    environment:
      - APPLICATION_PORT=3310
      - DATABASE_URL=postgres://ziadghalleb@host.docker.internal:5430/postgres
      - DATABASE_SCHEMA=public
      - DATABASE_SSL=false
      - FOREST_AUTH_SECRET=2c9d742d1f6c23ee0de4997030402f1ded57a64bffbfb682f2a3aee85ab7303eef712d1403f5e252ddc0b1ad76a47389
      - FOREST_ENV_SECRET=a5cb760eab4053b52ac1cf664bc5d5c68d3443dcbca2fa69a3a4b67afc635566
    ports:
      - "3310:3310"
    volumes:
      - ./:/usr/src/app
